baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'My New Hugo Site'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 1

[[menus.main]]
name = 'Blog'
pageRef = '/blog'
weight = 2

[[menus.main]]
name = 'Projects'
pageRef = '/projects'
weight = 3


[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
